# bash_aliases testing file

shopt -s expand_aliases

# Simple aliases
alias ls='ls --color=auto'
alias ll='ls -l'
alias la= 'ls -A'
alias gitlog='git log --graph --oneline --decorate --all'

# Cases like this are handled by the parser but it's good to have a test for it
my_function() {
    alias greet='echo Hello, World!'
}
